[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "devicetree"
language-servers = ["ginko_ls"]

[language-server.ginko_ls]
command = "ginko_ls"
config = { provideFormatter = false }

[[grammar]]
name = "vhdl"
source = { git = "https://github.com/SethGower/tree-sitter-vhdl.git", rev = "b6cb098d275299f93d84b465573050a83af45ed5" }
