#!/usr/bin/env bash

check_clone () {
    repo=$1
    directory=$2

    if [[ ! -d $2 ]]; then
        git clone $1 $2
    fi
}
# sudo check
echo "Checking sudo capabilities"
sudo ls &> /dev/null
if [ $? -ne 0 ]
then
  echo "Unable to get sudo, are you on the naughty list?"
  exit 1
fi
export OS=$(cat /etc/os-release | grep -E "\bID\b" | cut -d'=' -f2)
if [[ $OS == "arch" ]];
then
  export AUR_HELPER="paru"
fi

export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ -x $SCRIPT_DIR/$OS.sh ]]
then
  source $SCRIPT_DIR/${OS}.sh
fi

if [[ -z $(which rustup) ]]
then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

if [[ -x $(which nvim) ]]
then
  check_clone https://github.com/alemuller/tree-sitter-vhdl.git ~/.local/share/tree-sitter/tree-sitter-vhdl
  check_clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi
