#!/bin/bash
alias ls="ls --color"         # Force color for ls.
alias l="ls -lah --color"     # List in long format, include dotfiles.
alias la="ls -lah --color"    # List in long format, include dotfiles.
alias al="ls -lah --color"    # List in long format, include dotfiles.

alias dmesg="dmesg --color=always"

if [[ -x "$(command -v xstow)" ]]; then
    alias stow="xstow"
fi

alias cd="cdls"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias party='curl parrot.live'

alias gitlog="git log --date=local --format=\" * %h [%cd] %s\""
alias dot="git --git-dir=${HOME}/.dotfiles/.git --work-tree=${HOME}/.dotfiles"
alias xclip='xclip -selection c'
alias grep='grep --color=always'

if [[ -x "$(command -v nvim)" ]]; then
  alias vim="nvim"
  alias vi="nvim"
else
  alias nvim="vim"
  alias vi="vim"
fi

tkl(){
  for session; {
    tmux kill-session -t $session
  }
}

open(){
  xdg-open $1 &> /dev/null &
}

h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
fi

if [[ -x $(command -v thefuck) ]]; then
  eval $(thefuck --alias)
  eval $(thefuck --alias heck)
fi

alias please="sudo"
