#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
. "$HOME/.cargo/env"

# if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]
# then
# 	shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
# 	exec zsh $LOGIN_OPTION
# fi
