#!/bin/bash
source $HOME/.function

add_to_path ~/.local/bin
add_to_path /snap/bin
add_to_path ~/.yarn/bin
add_to_path /usr/local/go/bin/
add_to_path ~/.local/share/rust_hdl/target/release
add_to_path ~/.cargo/bin
add_to_path ~/go/bin
add_to_path ~/.local/share/flatpak/exports/bin


export XDG_DATA_DIRS="$XDG_DATA_DIRS:$HOME/.local/share/flatpak/exports/share/"
