#!/bin/bash
source $HOME/.function

add_to_path ~/.local/bin
add_to_path /snap/bin
add_to_path ~/.yarn/bin
add_to_path /usr/local/go/bin/
add_to_path ~/.local/share/rust_hdl/target/release
add_to_path ~/.cargo/bin
