# If wal is installed, use it
# [[ -x $(command -v wal) ]] &&(cat ~/.cache/wal/sequences &)
# Path to oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.custom_omz

# Add wisely, as too many plugins slow down shell startup.
plugins=(
  zsh-autosuggestions
  zsh-syntax-highlighting
  sudo
  direnv
)
ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh
source ~/.function

source ~/.alias
source ~/.path

if [ -f ~/.localconfig ]; then
  source ~/.localconfig
fi

fpath+=$ZSH_CUSTOM/completions

compinit

if [[ -f ~/.fzf.zsh ]];
then
    source ~/.fzf.zsh
fi

zstyle ':completion:*:*:nvim:*' file-patterns '^*.(aux|pdf|dvi|o):source-files' '*:all-files'

if [[ -x "$(command -v starship)" ]]; then
    eval "$(starship init zsh)"
fi

# sets the EDITOR env variable. Used for git commits and the like
if [[ -n $(which nvim) ]]; then
  export EDITOR=nvim
elif [[ -n $(which vim) ]]; then
  export EDITOR=vim
fi
export VISUAL="$EDITOR"
